create table VehiculosC12(
ID  INT IDENTITY NOT NULL PRIMARY KEY,
PATENTE VARCHAR(10) UNIQUE NOT NULL,
TIPO_ID INT, 
VELOCIDAD DECIMAL(4,2)
)

ALTER TABLE VehiculosC12 ALTER COLUMN VELOCIDAD DECIMAL (18,2)

select * from VehiculosC12

 SELECT ID, PATENTE, TIPO_ID, VELOCIDAD FROM VehiculosC12