create table usuarios(
ID INT IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(25) NOT NULL unique,
CLAVE VARCHAR(100) NOT NULL
);



INSERT INTO USUARIOS(NOMBRE,CLAVE)
VALUES ('Pipo123','Sprite22');

INSERT INTO USUARIOS(NOMBRE,CLAVE)
VALUES ('Natix','hola123');

SELECT * FROM usuarios